### ISSUE TITLE
Connection via I2C

### ISSUE THREAD

**Issue by Belayasmert** [jps2000/BNO080#4]
Hi jps2000,
i bought the dev. Kit from Hillcrest Labs for the BNO080. I went threw the starting guide and everything worked fine. But because i am not familiar using FRTOS i tried to write my oen code. Im also new to STMicrocontrollers and the HAL library. So i tried it like that.

  if(HAL_I2C_IsDeviceReady(&hi2c1, 0x4A, 100 ,100) != HAL_OK){
    HAL_UART_Transmit(&huart2, "Device not found! \n\r", strlen(msg), 0xFFFF);
  }
  else{
    HAL_UART_Transmit(&huart2, "Device found! \n\r", strlen(msg), 0xFFFF);
  }
If my NUCLEO-F411RE Board could reach the BNO080 should be enough to check if the Device is rdy?
I would be glad if you could help me.

greets

**Comment by jps2000** [comment]
Unfortunately I can not help. Do not know this NUCLEO stuff
